name: Cargo Format, Lint & Build

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  format_lint_build:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo fmt --check
      - run: cargo clippy --verbose
      - run: cargo build --verbose
